// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: beacon.proto

#ifndef PROTOBUF_beacon_2eproto__INCLUDED
#define PROTOBUF_beacon_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace beacon {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_beacon_2eproto();
void protobuf_AssignDesc_beacon_2eproto();
void protobuf_ShutdownFile_beacon_2eproto();

class Election;

// ===================================================================

class Election : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:beacon.Election) */ {
 public:
  Election();
  virtual ~Election();

  Election(const Election& from);

  inline Election& operator=(const Election& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Election& default_instance();

  void Swap(Election* other);

  // implements Message ----------------------------------------------

  inline Election* New() const { return New(NULL); }

  Election* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Election& from);
  void MergeFrom(const Election& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Election* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 is_leader = 1;
  void clear_is_leader();
  static const int kIsLeaderFieldNumber = 1;
  ::google::protobuf::int32 is_leader() const;
  void set_is_leader(::google::protobuf::int32 value);

  // optional uint32 last_node_id = 2;
  void clear_last_node_id();
  static const int kLastNodeIdFieldNumber = 2;
  ::google::protobuf::uint32 last_node_id() const;
  void set_last_node_id(::google::protobuf::uint32 value);

  // repeated uint32 added_node_id = 3;
  int added_node_id_size() const;
  void clear_added_node_id();
  static const int kAddedNodeIdFieldNumber = 3;
  ::google::protobuf::uint32 added_node_id(int index) const;
  void set_added_node_id(int index, ::google::protobuf::uint32 value);
  void add_added_node_id(::google::protobuf::uint32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      added_node_id() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_added_node_id();

  // repeated uint32 removed_node_id = 4;
  int removed_node_id_size() const;
  void clear_removed_node_id();
  static const int kRemovedNodeIdFieldNumber = 4;
  ::google::protobuf::uint32 removed_node_id(int index) const;
  void set_removed_node_id(int index, ::google::protobuf::uint32 value);
  void add_removed_node_id(::google::protobuf::uint32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      removed_node_id() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_removed_node_id();

  // @@protoc_insertion_point(class_scope:beacon.Election)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int32 is_leader_;
  ::google::protobuf::uint32 last_node_id_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > added_node_id_;
  mutable int _added_node_id_cached_byte_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > removed_node_id_;
  mutable int _removed_node_id_cached_byte_size_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_beacon_2eproto();
  friend void protobuf_AssignDesc_beacon_2eproto();
  friend void protobuf_ShutdownFile_beacon_2eproto();

  void InitAsDefaultInstance();
  static Election* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Election

// optional int32 is_leader = 1;
inline void Election::clear_is_leader() {
  is_leader_ = 0;
}
inline ::google::protobuf::int32 Election::is_leader() const {
  // @@protoc_insertion_point(field_get:beacon.Election.is_leader)
  return is_leader_;
}
inline void Election::set_is_leader(::google::protobuf::int32 value) {
  
  is_leader_ = value;
  // @@protoc_insertion_point(field_set:beacon.Election.is_leader)
}

// optional uint32 last_node_id = 2;
inline void Election::clear_last_node_id() {
  last_node_id_ = 0u;
}
inline ::google::protobuf::uint32 Election::last_node_id() const {
  // @@protoc_insertion_point(field_get:beacon.Election.last_node_id)
  return last_node_id_;
}
inline void Election::set_last_node_id(::google::protobuf::uint32 value) {
  
  last_node_id_ = value;
  // @@protoc_insertion_point(field_set:beacon.Election.last_node_id)
}

// repeated uint32 added_node_id = 3;
inline int Election::added_node_id_size() const {
  return added_node_id_.size();
}
inline void Election::clear_added_node_id() {
  added_node_id_.Clear();
}
inline ::google::protobuf::uint32 Election::added_node_id(int index) const {
  // @@protoc_insertion_point(field_get:beacon.Election.added_node_id)
  return added_node_id_.Get(index);
}
inline void Election::set_added_node_id(int index, ::google::protobuf::uint32 value) {
  added_node_id_.Set(index, value);
  // @@protoc_insertion_point(field_set:beacon.Election.added_node_id)
}
inline void Election::add_added_node_id(::google::protobuf::uint32 value) {
  added_node_id_.Add(value);
  // @@protoc_insertion_point(field_add:beacon.Election.added_node_id)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
Election::added_node_id() const {
  // @@protoc_insertion_point(field_list:beacon.Election.added_node_id)
  return added_node_id_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
Election::mutable_added_node_id() {
  // @@protoc_insertion_point(field_mutable_list:beacon.Election.added_node_id)
  return &added_node_id_;
}

// repeated uint32 removed_node_id = 4;
inline int Election::removed_node_id_size() const {
  return removed_node_id_.size();
}
inline void Election::clear_removed_node_id() {
  removed_node_id_.Clear();
}
inline ::google::protobuf::uint32 Election::removed_node_id(int index) const {
  // @@protoc_insertion_point(field_get:beacon.Election.removed_node_id)
  return removed_node_id_.Get(index);
}
inline void Election::set_removed_node_id(int index, ::google::protobuf::uint32 value) {
  removed_node_id_.Set(index, value);
  // @@protoc_insertion_point(field_set:beacon.Election.removed_node_id)
}
inline void Election::add_removed_node_id(::google::protobuf::uint32 value) {
  removed_node_id_.Add(value);
  // @@protoc_insertion_point(field_add:beacon.Election.removed_node_id)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
Election::removed_node_id() const {
  // @@protoc_insertion_point(field_list:beacon.Election.removed_node_id)
  return removed_node_id_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
Election::mutable_removed_node_id() {
  // @@protoc_insertion_point(field_mutable_list:beacon.Election.removed_node_id)
  return &removed_node_id_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace beacon

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_beacon_2eproto__INCLUDED
